---
title: Indivisible Acton Area MA
timezone: America/New_York
collections:
  events:
    title: Events
    output: true
  general-information:
    title: General Information
    output: true
  newsletters:
    title: Newsletters
    output: true
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  test:
    title: Test
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    phone-numbers:
      office-name: "(000) 000-0000"
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
- scope:
    path: ''
    type: becomeAMember
  values:
    main-image: 
    mailchimp-form-embed: 
subtitle: We are hundreds of Acton Area citizens supporting progressive policies through
  civic and electoral action at the national, state and local levels.
email: Indivisible.acton.ma@gmail.com
baseurl: 
url: www.indivisibleacton.org
twitter_username: IndActonMa
facebook_username: groups/indivisibleacton
background-image: "/uploads/20171118_112547.jpg"
member-count: 1061
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: |-
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127148508-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-127148508-1');
  </script>
