---
title: Indivisible Acton Massachusetts
timezone: America/New_York
collections:
  events:
    title: Events
    output: true
  general-information:
    title: General Information
    output: true
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  test:
    title: Test
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    phone-numbers:
      office-name: "(000) 000-0000"
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
- scope:
    path: ''
    type: becomeAMember
  values:
    main-image: 
    mailchimp-form-embed: 
subtitle: We are hundreds of Acton Area citizens supporting progressive policies through
  civic and electoral action Nationally and in the State
email: Indivisible.acton.ma@gmail.com
baseurl: 
url: www.indivisibleacton.org
twitter_username: inactonma
facebook_username: groups/indivisibleacton
background-image: "/uploads/20171118_112547.jpg"
member-count: 413
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: UA-99993052-1
